import { Department } from "./Department";

export const DepartmentRipley: { [key: string]: Department } = {
    'accesorios-y-complementos/optica': Department.Belleza,
    'belleza/maquillaje': Department.Belleza,
    'belleza/rostro': Department.Belleza,
    'belleza/cuerpo': Department.Belleza,
    'belleza/capilares/capilar-profesional': Department.Belleza,
    'belleza/dermocosmetica': Department.Belleza,
    'tecno/celulares': Department.Tecnologia,
    'tecno/computacion': Department.Tecnologia,
    'tecno/mundo-gamer': Department.Tecnologia,
    'tecno/fotografia-y-video': Department.Tecnologia,
    'tecno/smart-home': Department.Tecnologia,
    'tecno/smartwatches-y-smartbands': Department.Tecnologia,
    'tecno/television': Department.Tecnologia,
    'tecno/audio-y-musica': Department.Tecnologia,
    'electro/refrigeracion': Department.Electro,
    'electro/lavanderia': Department.Electro,
    'electro/climatizacion': Department.Electro,
    'electro/aseo': Department.Electro,
    'electro/smart-home': Department.Electro,
    'electro/cocina': Department.Electro,
    'electro/comercial-e-industrial': Department.Electro,
    'electro/salud-y-bienestar': Department.Electro,
    'electro/cuidado-personal': Department.Electro,
    'electro/costura-y-bordado': Department.Electro,
    'electro/electrodomesticos': Department.Electro,
}